# Versioned Properties
# NeoForge Properties, check https://neoforged.net/
build.neoforge=26.3.0.57-beta

# Additional Dependencies Properties
# yacl, check https://modrinth.com/mod/yacl/versions?g=26.3&l=neoforge
dep.yacl=3.9.7+26.3-neoforge
# modmenu is a Fabric-only mod, NeoForge uses its own mod list screen
dep.modmenu=unknown
dep.cit-resewn=unknown
dep.sodium=unknown
dep.ears=unknown

# Emotecraft integration (compile-only)
compat.emotecraft_api = 3.5.0-a.build.171
compat.player_anim_lib = 1.2.7+mc.26.3
