modLoader = "javafml"
loaderVersion = "[1,)"
license = "${mod_license}"
issueTrackerURL = "https://github.com/${github_mod_author}/SkinTotem26.x"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
side = "${neoforge_trick_side}"
displayURL = "https://modrinth.com/mod/skin-totem-2"
logoFile = "icon/icon.png"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[mixins]]
config = "${mod_id}-sodium.mixins.json"

[[mixins]]
config = "${mod_id}-yacl.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft}"
ordering = "NONE"
side = "CLIENT"
